### ISSUE TITLE
[Feature] Once.beenDone(scope, tag, times)

### ISSUE THREAD

**Issue by vanniktech** [jonfinerty/Once#13]
`Once.beenDone(scope, tag, times)` would only return true when that method has been called that specific number of times or more AND the item itself has not been done.

**Example 1**

```java
Once.beenDone(THIS_APP_INSTALL, "foo", 3); // false
Once.beenDone(THIS_APP_INSTALL, "foo", 3); // false
Once.beenDone(THIS_APP_INSTALL, "foo", 3); // true
Once.beenDone(THIS_APP_INSTALL, "foo", 4); // true
```

**Example 2**

```java
Once.beenDone(THIS_APP_INSTALL, "bar", 3); // false
Once.beenDone(THIS_APP_INSTALL, "bar", 3); // false
Once.beenDone(THIS_APP_INSTALL, "bar", 3); // true
Once.markDone("bar");
Once.beenDone(THIS_APP_INSTALL, "bar", 4); // false
```

What do you think of that?

My use case for that would be something rather annoying for the user and you don't want to show it always. (Ask them for rating the applications, inviting friends etc).

**Comment by jonfinerty** [comment]
Sounds like an interesting feature. I would say it fits better within the `toDo` method. Where you could call `toDo` multiple times and when you query `needToDo` you can optionally give it a threshold like you where showing of how many times it needs to be marked before returning true. 

But thanks for the input! I will have a better think about implementations and get back to you with something more thought through.

**Comment by vanniktech** [comment]
Thanks for the fast reply. To be honest I don't like the flow of that since you'd have to call `toDo` multiple times or do you want to increment the threshold when a call to `needToDo` is made? I'd prefer the latter way. In any case the initial call to `toDo` bugs me a bit.

**Comment by jonfinerty** [comment]
Sorry I may not have been vary clear in my last comment. The usage I was thinking off would be:

```java
Once.toDo(THIS_APP_INSTALL, "bar");
Once.needToDo("bar", 2); // false
Once.toDo(THIS_APP_INSTALL, "bar");
Once.needToDo("bar", 2); // true
Once.needToDo("bar", 3); // false
```

My main reasoning is that querying `beenDone` or `needToDo` shouldn't change state, they merely report state. The main reason behind having both mark/been and toDo/needToDo is to split up the read/write methods in the API.

**Comment by vanniktech** [comment]
It seems like to me that we have to call a lot of methods (always `toDo` and `needToDo`). How about we go with a complete different approach and don't reuse the names.

**Example 1**

```java
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // False
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // False
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // True
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 4); // True
```

**Example 2**

```java
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // False
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // False
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 3); // True
Once.markDoneAtLeast("askedUserToRateApp");
Once.beenDoneAtLeast(THIS_APP_INSTALL, "askedUserToRateApp", 4); // False
```

**Comment by jonfinerty** [comment]
Can I demonstrate using another, very similar, use case. Two screens: Screen A - A screen where you want to show a 'please rate our app' dialog', but only when the user has visited Screen B (perhaps containing functionality that usage of shows engagement) three times.

Now with your proposed API I can't see a way to implement this.  You'd have `Once.beenDoneAtLeast(THIS_APP_INSTALL, "showRatingDialog", 3);` calls in Screen B in order to track whether or not the user has seen Screen B three times. But you'd also have the same call made in Screen A to check whether to show the dialog. The problem here is that the calls made in Screen A would be bumping up the counter erroneously.

**Comment by vanniktech** [comment]
You're right with your last point there. However I would not differentiate between Screen A & Screen B since I'd display the dialog right after the user did something meaningful. So the transition from A to B does not really bother me.

Why would I want to display a dialog in Screen A when the user navigated back from B where he did something meaningful which provided him some benefit? I'd rather ask him instantly on Screen B after he did something to rate my app.

Also theoretically speaking he could just close the app on Screen B, open it at some point again and navigates back to A. Now getting the 'rate my app dialog' just seems weird as the user has most probably forgotten that he did do something earlier the day.

If you really do want we could do the following

```java
Once.beenDone(scope, tag, times); // Calls it with true by default
Once.beenDone(scope, tag, times, shouldIncrementCounter); // Let the consumer decide whether he wants to increment the counter or not
```

**Comment by vanniktech** [comment]
@jonfinerty  any updates to this one?

**Comment by dudadayan** [comment]
+1

**Comment by jonfinerty** [comment]
@vanniktech @dudadayan well, after probably the longest wait on a github issue ever, I've finally made some progress on this, you can see the start of the implementation here: https://github.com/jonfinerty/Once/compare/count_checker?expand=1 I need to update the javadoc and put an example of usage in the sample app, but hopefully that should be done this evening

**Comment by vanniktech** [comment]
@jonfinerty nice I'm very much liking this :+1:
