### ISSUE TITLE
Upgrade to 1.0.0 

### ISSUE THREAD

**Issue by rkrater** [jonfinerty/Once#18]
I've upgrade from 0.5.0 to 1.0.0

My app crashes on `Once.initialise(this);` in my Application class. I've included the logcat dump

[logcat.txt](https://github.com/jonfinerty/Once/files/167522/crash.txt)

**Comment by jonfinerty** [comment]
Ah I did not consider this. You'll have values from v0.5.0 and I changed the format of how these are stored in v1.0.0. I need to have a think about a solution. Thanks for the heads up, I'll look into this deeper tonight.

**Comment by rkrater** [comment]
My app is still in development so doesn't affect me but just wanted to let you know

**Comment by jonfinerty** [comment]
I've pushed a fix which lets v1.0.1+ load the format I used previously. So hopefully it won't crash and anyone who was using it in production will keep their data.
