### ISSUE TITLE
Using Once right after app starts causes thread to freeze

### ISSUE THREAD

**Issue by Pkmmte** [jonfinerty/Once#21]
Using any Once method right when the application starts causes the entire thread to freeze. In my case, I'd like to use this library in my MainActivity to know if I should show the user an onboarding screen. However, calling `Once.beenDone("seen_onboarding")` caused a blank screen to be shown.

I was able to replicate this effect on a sample app quite easily with the following steps:
1. Call `Once.initialise(this)` in the app's Application class `onCreate()`.
2. Call any Once method inside the MainActivity's `onCreate()`.

Doing this will cause a blank screen. It's pretty straightforward but I can provide the sample app code if needed. This only happens in version 1.0.2 of the library. I'm guessing it's because the asynchronous loading never wakes up the thread that called it before it finished loading.

**Comment by jonfinerty** [comment]
Thanks for raising this, I'll look into it today hopefully. In the meantime it's probably best to just downgrade to v1.0.1

**Comment by jonfinerty** [comment]
This should be fixed now if you grab v1.0.3
