### ISSUE TITLE
[Feature Request] Allow us to specify listeners for Once.initialise() completion

### ISSUE THREAD

**Issue by Pkmmte** [jonfinerty/Once#23]
I really enjoy using this library but my only issue with it is the time it takes to initialize. 

I understand that Once initializes in the background but using it blocks the calling thread until it has finished initializing. In my app, I use Once.beenDone() in the onCreate() method of my first activity therefore the main thread gets blocked during startup. I would prefer it if there was some way to attach listeners to notify us as soon as Once.initialise() has finished running. :)

**Comment by jonfinerty** [comment]
Thanks for the request, good idea. Surprisingly how tricky it is to get a library to work on startup without blocking the main thread. I'll have a look into this week hopefully.

**Comment by jonfinerty** [comment]
I've got a branch around this, https://github.com/jonfinerty/Once/tree/initialisation_callback any thoughts? The implementation is a little clumsy (nested listeners).

**Comment by Pkmmte** [comment]
It looks fine to me! I'm not a fan of the callCount approach and it would have been nice to be able to register multiple listeners but that's nothing a little wrapper can't fix! :) 

I've been testing that code for a few days now and it seems to be working well.
