### ISSUE TITLE
constant prefs filename

### ISSUE THREAD

**Issue by emakar** [jonfinerty/Once#24]
SharedPreferences in PersistedMap are created with name:
```
PersistedMap.class.getSimpleName() + mapName
```
however if class is obfuscated it might have different name on further app versions, so I'm guessing it would be better to protect class from obfuscation or give preferences a constant name (or allow to specify it on client side)

**Comment by jonfinerty** [comment]
Ah. That is a very good point which I hadn't considered.

Constant name sounds like a simpler option. 

However, this raising a bigger issue, which is would be a breaking change. If the name of the prefs changes, then any new calls to Once will return incorrect results. This is already happening though if two builds obfuscate the class into different names, a pretty bad bug.

Perhaps the best choice is to replace the `PersistedMap.class.getSimpleName()` section with `"PersistedMap"` which would ensure existing, non-obsfucated clients wouldn't break
