### ISSUE TITLE
[Feature request] Allow us to retrieve the timestamp when an event was last marked done

### ISSUE THREAD

**Issue by GSala** [jonfinerty/Once#28]
I'm using Once to mark when app data needs to be synchronized (every 20 minutes for example) and it could be useful to have a method that returns the Date when a task was last marked as done.

**Comment by jonfinerty** [comment]
That's a great idea! Any thoughts on what your preferred interface would be for it? `Once.when(tag)` maybe. Would returning when it was last marked done be enough, or every time it was marked done?

**Comment by GSala** [comment]
I was thinking about only getting the last time something was marked as done. I'll be using it to show the user the last time the data was refreshed. I can't think of a use case where you need all the previous timestamps.

For that reason I thought the interface could be something like `Once.lastDone(tag)` or `Once.lastMarkedDone(tag)`.

**Comment by jonfinerty** [comment]
`Once.lastDone(tag)` seems good, and I guess a null if it's never been done.

**Comment by GSala** [comment]
Sounds great  :+1:

**Comment by jonfinerty** [comment]
Cool, I'll hopefully get to this, this weekend. Thanks for the request!

**Comment by jonfinerty** [comment]
Got this on a branch - https://github.com/jonfinerty/Once/pull/29 - I'll merge soon

**Comment by jonfinerty** [comment]
All done, if you update to v1.2.1 you should have this feature, I'm going to close this now, but feel free to re-open or open a new one with any feedback on this feature. Thanks!
