### ISSUE TITLE
I think there is a bug

### ISSUE THREAD

**Issue by youngzm** [jonfinerty/Once#36]
If I uninstall the app or clear data,it will reset all buttons.But I don't want it happen,How can I do?

**Comment by jonfinerty** [comment]
Hi, Once persists all its data with sharedpreferences. So if the app is wiped or uninstalled that's gone too. At the moment this is working as intended as I didn't want to pollute the users phone with files that wouldn't get cleaned up. A future feature could be to have an option to store data outside this sandbox but then it might be tampered with by other apps or the user. In the meantime you'll need to either store this information server side (if you have one) or write it to a file yourself.

**Comment by Harti** [comment]
Interestingly, after a clean reinstall, my app claims that `Once.beenDone(Once.THIS_APP_INSTALL, "tutorial.skipped")` is true, even if I `clearDone` it before uninstalling. Nowhere in my app am I setting `markDone` before the boolean is returned. Is there a good way to debug this?

**Comment by jonfinerty** [comment]
@Harti If you can write a failing test that would be amazing. Failing that you should be able to debug your app, set a breakpoint and then inspect the contents of the underlying collections in Once, theres an in-memory map that stores tags and when they were last seen. Behind that it's stored in sharedpreferences, I can't think of way that your sharedpreferences are surviving a clean reinstall, unless there's something unusual your doing?

**Comment by AntonyGolovin** [comment]
@Harti maybe you have `allowBackup=true` in your AndroidManifest.xml?

**Comment by Harti** [comment]
@AntonyGolovin yep, I do. Good catch! I'm assuming removing it will fix my issue (I'm unable to test it right now)?

**Comment by AntonyGolovin** [comment]
Yes, `allowBackup` also preserves SharedPreferences.

**Comment by inmyth** [comment]
Is there a possibility of implementing some sort of XXX_RESET_BACKUP flag that resets the values restored from allowBackup ? I think app reinstall should give clean slate on guide, introduction status.
