### ISSUE TITLE
Provide a changelog

### ISSUE THREAD

**Issue by vernazza** [jonfinerty/Once#46]
Please, provide a quick changelog.
It's not clear what changed between version 1.2.2 and version 1.3.0

**Comment by jonfinerty** [comment]
Hi, yes I'll backfill this. In the short-term, the changes were mostly library updates, bug fixes and removing the initial async loading of shared preferences which causes a lot of complexity in the code to save on a couple ms of thread usage. (so I'd advise turning on StrictMode after initialisation).

**Comment by jonfinerty** [comment]
I've added a crude changelog, and for any future changes I'll add it it.
