### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by markini** [jonfinerty/Once#47]
```
Caused by java.util.ConcurrentModificationException
java.util.ArrayList$Itr.next (ArrayList.java:860)
jonathanfinerty.once.Once.beenDone (Once.java:254)
jonathanfinerty.once.Once.beenDone (Once.java:219)
jonathanfinerty.once.Once.beenDone (Once.java:204)
...
```

"Culprit" is the list inside the map in `PersistedMap.java`
https://github.com/jonfinerty/Once/blob/master/once/src/main/java/jonathanfinerty/once/PersistedMap.java#L18

Synchronizing access to the list at it is now, could be a little bit of a [pain](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#synchronizedList(java.util.List)).

Might consider annotating every public static function in `Once.java` with `synchronized`. I think this step would at worst cost only a few milliseconds.

**Comment by jonfinerty** [comment]
More than a year later, I think this is fixed in the 1.3.1 version, if not feel free to reopen
