### ISSUE TITLE
Could not find com.jonathanfinerty.once:once:1.2.2

### ISSUE THREAD

**Issue by stereodenis** [jonfinerty/Once#54]
> Could not resolve all files for configuration ':app:releaseRuntimeClasspath'.
   > Could not find com.jonathanfinerty.once:once:1.2.2.
     Searched in the following locations:
       - https://maven.google.com/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - https://repo.maven.apache.org/maven2/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - file:/root/.m2/repository/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - https://plugins.gradle.org/m2/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - file:/builds/wilix/clients/mobile/node_modules/react-native/android/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - file:/builds/wilix/clients/mobile/node_modules/jsc-android/dist/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - https://dl.google.com/dl/android/maven2/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom
       - https://jitpack.io/com/jonathanfinerty/once/once/1.2.2/once-1.2.2.pom

**Comment by stereodenis** [comment]
@jonfinerty do you know whats wrong?

**Comment by jonfinerty** [comment]
At version 1.3.0 I switched from hosting the package on jcenter/bintray to mavenCentral, I did not upload prior versions to maven, so 1.2.2 has never been on maven. If your build was previously working, potentially the final hosting/caching of the 1.2.2 has gone away. 

I recommend updating to the lastest version - 1.3.1
